#!/bin/bash

if [[ -z "${HISTORIC_TAG_DATA_PATH}" ]]; then
    echo "[WARNING] You need to define HISTORIC_TAG_DATA_PATH, that will contain historic tag data. Exiting."
    exit 1
fi

function build {
    docker build -t daccs-image-updater:0.1 .
}

function run {
    if [[ -z "${GITHUB_TOKEN}" ]]; then
        echo "[ERROR] Missing GITHUB_TOKEN. Exiting."
        exit 1
    fi

    docker run -v ${HISTORIC_TAG_DATA_PATH}:/opt/local/src/daccs-image-updater/data \
     -e GITHUB_TOKEN=$GITHUB_TOKEN \
     -e ENV_FILE=$ENV_FILE \
     -e CONFIG_FILE=$CONFIG_FILE \
     -e DRY_RUN=$DRY_RUN \
     daccs-image-updater:0.1 ./main.sh

     exit $?
}

function test {
    docker run -v ${HISTORIC_TAG_DATA_PATH}:/opt/local/src/daccs-image-updater/data \
     -e ENV_FILE=$ENV_FILE \
     -e CONFIG_FILE=$CONFIG_FILE \
     -e DRY_RUN=$DRY_RUN \
     daccs-image-updater:0.1 /bin/sh -c 'cd tests/integration && ./integration_test_runner.sh'

    exit $?
}

function clean-data {
    sudo rm -f ${HISTORIC_TAG_DATA_PATH}/*.old
    sudo rm -f ${HISTORIC_TAG_DATA_PATH}/*.new
    sudo rm -f ${HISTORIC_TAG_DATA_PATH}/*.log
}

function build-test {
    build
    test
}

function build-run {
    build
    run
}

function default {
    help
}

function help {
    echo "Build and test docker image"
    echo ""
    echo "Example : HISTORIC_TAG_DATA_PATH=/historic-tag-data $0 build-test"
    echo ""
    echo "Actions:"
    compgen -A function | grep -v help | grep -v default | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}