#!/bin/bash

function build {
    docker build -t daccs-image-updater:0.1 .
}

function run {
    docker run daccs-image-updater:0.1 ./main.sh
}

function test {
    docker run daccs-image-updater:0.1 python ./tests/integration/integration_test_runner.sh
}

function build-test {
    build
    test
}

function build-run {
    build
    run
}

function default {
    help
}

function help {
    echo "Build and test docker image"
    echo ""
    echo "Example : $0 build"
    echo ""
    echo "Actions:"
    compgen -A function | grep -v help | grep -v default | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}